scripts: Better notifications in dmenuaddmusic script

diff --git a/home/.local/bin/dmenuaddmusic b/home/.local/bin/dmenuaddmusic
--- a/home/.local/bin/dmenuaddmusic
+++ b/home/.local/bin/dmenuaddmusic
@@ -3,17 +3,36 @@
 # This script will use ytfzf to scrape youtube for the text entered and add url
 # to mpd queue
 
+notify(){
+    notify-send "${1}" -a "Music Player" -i "${XDG_DATA_HOME}/icons/my_icons/music.png"
+    # notify-send "${1}" -a "Music Player" -i "/home/sbdaule/.local/share/icons/my_icons/music.png"
+}
+
 addmusic(){
     ytlink="$1"
-    yt-dlp -g -f bestaudio "$ytlink" | xargs mpc insert
-    title=$(yt-dlp -e "$ytlink")
-    thumbnail_url=$(yt-dlp --get-thumbnail "$ytlink")
-    curl "$thumbnail_url" -o /tmp/mpc-thumbnail.webp
-    notify-send -a "mpd" "$title" "Added to mpd playlist" -i /tmp/mpc-thumbnail.webp
+    cd ~/multimedia/music/ytdlp/
+    file=$(yt-dlp -f bestaudio -x --audio-format mp3 "$ytlink" --embed-thumbnail -O after_move:filepath)
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        notify-send "Download failed with exit code $ret"
+        exit $ret
+    fi
+    file=$(echo $file | cut -d '/' -f 7)
+    # notify-send "${file} downloaded" -a "Music Player"
+    notify "${file} downloaded"
+    mpc update
+    sleep 1
+    mpc insert "ytdlp/${file}"
 }
 
 if [[ -z $1 ]]; then
     ytlink=$(ytfzf -DL)
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        # notify-send "Failed to fetch video link" -a "Music Player"
+        notify "Failed to fetch video link"
+        exit $ret
+    fi
     addmusic "$ytlink"
 elif [[ $1 == "-l" ]]; then
     if [[ -z $2 ]]; then
